package com.codex.witchweapon;

import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import org.json.JSONObject;

/** Generated by tools/generate_original_combat_energy.py; no runtime resource dependency. */
final class OriginalCombatRules {
    // Original 2020 source SHA-256:
    // servant.txt 9a2e655accc4c8787109f23d42a64db21cd8c2ea62ed8d26f0277492fc3e033b
    // servantrankinfo.txt 5079c0ad8bad0b28ff522f9df16f262b1099baeb6945449b2ea5b8d64fccf9af
    // servantequip.txt 433b5826e8fe0ab86def966a0d65bbe288f7ea996703b54e3bedf991110ef474
    // Audited weapon links cf7b58a889d46d915650b7a5205ab45e44c0ab24a8b3e80f32c6e695437f83ea
    // servant, first rank, last rank, ERT, ERKT, ERA, ERI; protocol units are 1/10000.
    // Every original rank row is checked before identical consecutive ranks are combined.
    private static final long[][] ENERGY={
        {10010001L,1L,10L,0L,560000L,0L,30000L},
        {10010101L,1L,10L,0L,470000L,60000L,60000L},
        {10010201L,1L,10L,0L,310000L,40000L,40000L},
        {10010301L,1L,10L,0L,270000L,80000L,50000L},
        {10010401L,1L,10L,0L,200000L,30000L,40000L},
        {10010501L,1L,10L,0L,310000L,40000L,40000L},
        {10010601L,1L,10L,0L,310000L,40000L,40000L},
        {10010701L,1L,10L,750000L,440000L,0L,30000L},
        {10010801L,1L,10L,0L,350000L,40000L,20000L},
        {10010901L,1L,10L,0L,330000L,80000L,20000L},
        {10011001L,1L,10L,0L,350000L,40000L,20000L},
        {10011101L,1L,10L,0L,270000L,30000L,10000L},
        {10011201L,1L,10L,0L,350000L,40000L,20000L},
        {10011301L,1L,10L,0L,270000L,30000L,10000L},
        {10011401L,1L,10L,0L,400000L,40000L,0L},
        {10011501L,1L,10L,0L,330000L,40000L,30000L},
        {10011601L,1L,10L,0L,270000L,0L,20000L},
        {10011701L,1L,10L,0L,310000L,40000L,40000L},
        {10011801L,1L,10L,0L,380000L,40000L,10000L},
        {10011901L,1L,10L,0L,330000L,40000L,30000L},
        {10012001L,1L,10L,0L,220000L,0L,40000L},
        {10012101L,1L,10L,0L,220000L,60000L,30000L},
        {10012201L,1L,10L,0L,380000L,0L,20000L},
        {10012301L,1L,10L,0L,330000L,40000L,30000L},
        {10012401L,1L,10L,0L,350000L,40000L,20000L},
        {10012501L,1L,10L,0L,220000L,60000L,30000L},
        {10012701L,1L,10L,0L,330000L,80000L,20000L},
        {10012801L,1L,10L,0L,290000L,170000L,20000L},
        {10012901L,1L,10L,0L,160000L,190000L,30000L},
        {10013001L,1L,10L,0L,380000L,380000L,30000L},
        {10013101L,1L,10L,0L,280000L,0L,10000L},
        {10013201L,1L,10L,0L,160000L,130000L,40000L},
        {10013301L,1L,10L,0L,160000L,250000L,10000L},
        {10013501L,1L,10L,0L,500000L,130000L,30000L},
        {10013701L,1L,10L,0L,250000L,0L,30000L},
        {10013801L,1L,10L,0L,330000L,80000L,20000L},
        {10013901L,1L,10L,0L,220000L,130000L,10000L},
        {10014001L,1L,10L,40000L,330000L,80000L,0L},
        {10014101L,1L,10L,0L,110000L,110000L,50000L},
        {10014201L,1L,10L,0L,290000L,130000L,30000L},
        {10014301L,1L,10L,0L,330000L,80000L,20000L},
    };
    // servant, weapon, spell, trigger, followed only by audited directly linked buff IDs.
    private static final long[][] WEAPON_EFFECTS={
        {10010001L,1701000101L,91000000L,92000000L},
        {10010001L,1701000102L,91000010L,92000010L,93000010L},
        {10010101L,1701010101L,91000020L,92000020L},
        {10010101L,1701010102L,91000030L,92000030L,93000030L},
        {10010101L,1701010103L,91000040L,92000040L,93000040L},
        {10010101L,1701010103L,91000041L,92000041L},
        {10010101L,1701010103L,91000042L,92000042L},
        {10010401L,1701040101L,91000090L,92000090L,93000090L,93000091L},
        {10010401L,1701040102L,91000100L,92000100L},
        {10010401L,1701040102L,91000101L,92000101L,93000100L},
        {10010501L,1701050101L,91000110L,92000110L},
        {10010501L,1701050102L,91000120L,92000120L},
        {10010601L,1701060101L,91000130L,92000130L,93000130L},
        {10010601L,1701060101L,91000131L,92000131L},
        {10010701L,1701070101L,91000150L,92000150L,93000150L},
        {10010701L,1701070102L,91000160L,92000160L},
        {10010701L,1701070102L,91000161L,92000161L,93000160L},
        {10010801L,1701080101L,91000170L,92000170L,93000170L},
        {10010801L,1701080101L,91000171L,92000171L},
        {10010801L,1701080102L,91000180L,92000180L},
        {10010901L,1701090101L,91000190L,92000190L,93000190L},
        {10010901L,1701090102L,91000200L,92000200L,93000200L},
        {10011001L,1701100101L,91000210L,92000210L,93000210L},
        {10011001L,1701100101L,91000211L,92000211L,93000210L},
        {10011001L,1701100102L,91000220L,92000220L,93000220L,93000221L},
        {10011001L,1701100102L,91000221L,92000221L,93000220L,93000221L},
        {10011001L,1701100102L,91000222L,92000222L,93000220L,93000221L},
        {10011001L,1701100103L,91000230L,92000230L,93000230L},
        {10011001L,1701100103L,91000231L,92000231L,93000230L},
        {10011001L,1701100103L,91000232L,92000232L,93000230L,93000231L},
        {10011101L,1701110101L,91000240L,92000240L,93000240L},
        {10011101L,1701110102L,91000250L,92000250L,93000250L,93000251L,93000252L},
        {10011101L,1701110102L,91000251L,92000251L},
        {10011101L,1701110102L,91000252L,92000252L,93000252L},
        {10011101L,1701110102L,91000253L,92000253L,93000251L,93000252L},
        {10011201L,1701120102L,91000270L,92000270L,93000270L},
        {10011201L,1701120102L,91000271L,92000271L,93000270L},
        {10011201L,1701120102L,91000272L,92000272L,93000270L},
        {10011301L,1701130101L,91000280L,92000280L,93000280L},
        {10011401L,1701140101L,91000290L,92000290L},
        {10011401L,1701140101L,91000291L,92000291L,93000290L},
        {10011401L,1701140102L,91000300L,92000300L,93000300L},
        {10011401L,1701140102L,91000301L,92000301L,93000300L},
        {10011501L,1701150101L,91000310L,92000310L},
        {10011501L,1701150101L,91000311L,92000311L,93000310L},
        {10011601L,1701160101L,91000330L,92000330L,93000330L},
        {10011701L,1701170101L,91000350L,92000350L,93000350L},
        {10011701L,1701170101L,91000351L,92000351L,93000350L},
        {10011901L,1701190101L,91000380L,92000380L},
        {10011901L,1701190101L,91000381L,92000381L},
        {10011901L,1701190102L,91000390L,92000390L,93000390L},
        {10012001L,1701200101L,91000400L,92000400L},
        {10012001L,1701200102L,91000410L,92000410L,93000410L},
        {10012001L,1701200102L,91000411L,92000411L,93000410L},
        {10012101L,1701210101L,91000420L,92000420L,93000420L},
        {10012101L,1701210101L,91000421L,92000421L,93000420L},
        {10012101L,1701210102L,91000430L,92000430L,93000430L},
        {10012101L,1701210102L,91000431L,92000431L,93000430L},
        {10012101L,1701210102L,91000432L,92000432L},
        {10012201L,1701220101L,91000440L,92000440L,93000440L},
        {10012201L,1701220101L,91000441L,92000441L},
        {10012201L,1701220101L,91000442L,92000442L},
        {10012301L,1701230101L,91000460L,92000460L},
        {10012301L,1701230102L,91000470L,92000470L,93000470L},
        {10012301L,1701230102L,91000471L,92000471L},
        {10012301L,1701230102L,91000472L,92000472L},
        {10012301L,1701230102L,91000473L,92000473L},
        {10012401L,1701240102L,91000491L,92000491L,93000490L},
        {10012501L,1701250101L,91000500L,92000500L},
        {10012501L,1701250102L,91000510L,92000510L},
        {10012701L,1701270101L,91000520L,92000520L},
        {10012801L,1701280101L,91000530L,92000530L,93000530L,93000531L},
        {10012801L,1701280101L,91000531L,92000531L,93000530L,93000531L},
        {10012801L,1701280101L,91000532L,92000532L,93000530L},
        {10012801L,1701280102L,91000540L,92000540L,93000540L},
        {10012801L,1701280102L,91000541L,92000541L,93000540L},
        {10012901L,1701290102L,91000560L,92000560L,93000560L},
        {10013001L,1701300101L,91000570L,92000570L,93000570L,93000571L},
        {10013001L,1701300101L,91000571L,92000571L,93000570L,93000571L},
        {10013001L,1701300102L,91000580L,92000580L},
        {10013201L,1701320102L,91000610L,92000610L,93000610L},
        {10013201L,1701320102L,91000611L,92000611L,93000610L},
        {10013201L,1701320102L,91000612L,92000612L,93000610L},
        {10013301L,1701330101L,91000620L,92000620L,93000620L},
        {10013701L,1701370101L,91000640L,92000640L,93000640L},
        {10013701L,1701370101L,91000641L,92000641L,93000640L},
        {10013801L,1701380101L,91000650L,92000650L,93000650L},
        {10013801L,1701380101L,91000651L,92000651L,93000650L},
        {10013901L,1701390101L,91000660L,92000660L,93000660L},
        {10013901L,1701390101L,91000661L,92000661L,93000660L},
        {10014101L,1701410101L,91000680L,92000680L,93000681L},
        {10014101L,1701410101L,91000681L,92000681L,93000680L,93000681L},
        {10014101L,1701410102L,91000690L,92000690L,93000690L,93000691L},
        {10014101L,1701410102L,91000691L,92000691L,93000690L,93000691L},
        {10014201L,1701420101L,91000700L,92000700L},
    };

    private OriginalCombatRules(){}

    static void apply(JSONObject state,JSONObject catalog,ProtoWire role)throws Exception{
        int roleLevel=WeaponFurnace.roleLevel(state,catalog);
        JSONObject owned=state.optJSONObject("ownedServants");
        if(owned==null){role.set(100,roleLevel);return;}

        Map<ProtoWire.Field,byte[]> servants=new LinkedHashMap<ProtoWire.Field,byte[]>();
        Map<Long,Long> spellLevels=new HashMap<Long,Long>();
        Map<Long,Long> triggerLevels=new HashMap<Long,Long>();
        Map<Long,Long> buffLevels=new HashMap<Long,Long>();
        for(ProtoWire.Field field:role.fields){
            if(field.number!=2 || field.type!=2)continue;
            ProtoWire info=ProtoWire.parse(field.data);
            long sid=info.number(1,0),wid=info.number(14,0);
            String key=Long.toString(sid);
            if(!owned.has(key))continue;
            ProtoWire saved=LocalEconomy.decode(owned.getString(key));
            long rank=saved.number(4,1),weaponLevel=saved.number(12,1);
            if(weaponLevel<1 || weaponLevel>Integer.MAX_VALUE)
                throw new IOException("Invalid saved weapon level for servant "+sid);
            long[] energy=energy(sid,rank);
            info.clear(9);
            for(int index=3;index<7;index++)info.add(9,energy[index]);
            servants.put(field,info.bytes());

            Set<Long> referencedTriggers=new HashSet<Long>(info.integers(6));
            for(long[] effect:WEAPON_EFFECTS){
                if(effect[0]!=sid || effect[1]!=wid)continue;
                if(!referencedTriggers.contains(effect[3]))
                    throw new IOException("Audited weapon trigger absent from selected servant: "+effect[3]);
                assign(spellLevels,effect[2],weaponLevel,"spell");
                assign(triggerLevels,effect[3],weaponLevel,"trigger");
                for(int index=4;index<effect.length;index++)
                    assign(buffLevels,effect[index],weaponLevel,"buff");
            }
        }

        ProtoWire unit=ProtoWire.parse(role.data(102));
        update(unit,1,2,spellLevels,"spell");
        update(unit,4,2,triggerLevels,"trigger");
        update(unit,2,3,buffLevels,"buff");
        // Commit only after all references and shared-effect levels have been validated.
        for(Map.Entry<ProtoWire.Field,byte[]> change:servants.entrySet())
            change.getKey().data=change.getValue();
        if(!spellLevels.isEmpty())role.set(102,unit.bytes());
        role.set(100,roleLevel);
    }

    private static long[] energy(long servant,long rank)throws IOException{
        for(long[] row:ENERGY)
            if(row[0]==servant && rank>=row[1] && rank<=row[2])return row;
        throw new IOException("Original energy row absent for servant "+servant+" rank "+rank);
    }

    private static void assign(Map<Long,Long> levels,long id,long level,String kind)throws IOException{
        Long previous=levels.get(id);
        if(previous!=null && previous.longValue()!=level)
            throw new IOException("Conflicting selected weapon levels for shared "+kind+" "+id);
        levels.put(id,level);
    }

    private static void update(ProtoWire unit,int fieldNumber,int idField,
                               Map<Long,Long> levels,String kind)throws IOException{
        Set<Long> found=new HashSet<Long>();
        for(ProtoWire.Field field:unit.fields){
            if(field.number!=fieldNumber || field.type!=2)continue;
            ProtoWire info=ProtoWire.parse(field.data);
            long id=info.number(idField,0);
            Long level=levels.get(id);
            if(level==null)continue;
            if(!found.add(id))throw new IOException("Duplicate combat "+kind+" ID "+id);
            info.set(1,level.longValue());field.data=info.bytes();
        }
        if(found.size()!=levels.size()){
            Set<Long> missing=new HashSet<Long>(levels.keySet());missing.removeAll(found);
            throw new IOException("Audited combat "+kind+" IDs absent: "+missing);
        }
    }
}
