"""Generate source-only combat rules from preserved 2020 tables and audited links.

No game resources, APKs, or deployment files are changed. Run with --check to
verify that OriginalCombatRules.java still matches the original table inputs.
"""
import argparse
import base64
import csv
import hashlib
import io
import json
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]
ORIGINAL = Path(r"D:\Project\魔女兵器工程恢复\原版\可读脚本与配置\配置\clientexel")
ENERGY_COLUMNS = (
    "energy_restore_time", "energy_restore_killing_time",
    "energy_restore_attacked", "energy_restore_injured",
)


def table(path):
    rows = list(csv.DictReader(io.StringIO(path.read_text(encoding="utf-8-sig"))))[2:]
    return {int(row["ID"]): row for row in rows if row.get("ID")}


def wire(data):
    offset = 0

    def varint():
        nonlocal offset
        value = 0
        for shift in range(0, 70, 7):
            if offset >= len(data):
                raise ValueError("Truncated protobuf varint")
            byte = data[offset]
            offset += 1
            value |= (byte & 127) << shift
            if byte < 128:
                return value
        raise ValueError("Invalid protobuf varint")

    fields = []
    while offset < len(data):
        tag = varint()
        number, kind = tag >> 3, tag & 7
        if number <= 0:
            raise ValueError("Invalid protobuf tag")
        if kind == 0:
            value = varint()
        else:
            size = varint() if kind == 2 else 8 if kind == 1 else 4 if kind == 5 else -1
            if size < 0 or offset + size > len(data):
                raise ValueError("Invalid protobuf field length")
            value = data[offset:offset + size]
            offset += size
        fields.append((number, kind, value))
    return fields


def number(fields, key):
    return next((value for field, kind, value in fields if field == key and kind == 0), 0)


JAVA = '''package com.codex.witchweapon;

import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import org.json.JSONObject;

/** Generated by tools/generate_original_combat_energy.py; no runtime resource dependency. */
final class OriginalCombatRules {
    // Original 2020 source SHA-256:
%HASHES%
    // servant, first rank, last rank, ERT, ERKT, ERA, ERI; protocol units are 1/10000.
    // Every original rank row is checked before identical consecutive ranks are combined.
    private static final long[][] ENERGY={
%ENERGY%
    };
    // servant, weapon, spell, trigger, followed only by audited directly linked buff IDs.
    private static final long[][] WEAPON_EFFECTS={
%EFFECTS%
    };

    private OriginalCombatRules(){}

    static void apply(JSONObject state,JSONObject catalog,ProtoWire role)throws Exception{
        int roleLevel=WeaponFurnace.roleLevel(state,catalog);
        JSONObject owned=state.optJSONObject("ownedServants");
        if(owned==null){role.set(100,roleLevel);return;}

        Map<ProtoWire.Field,byte[]> servants=new LinkedHashMap<ProtoWire.Field,byte[]>();
        Map<Long,Long> spellLevels=new HashMap<Long,Long>();
        Map<Long,Long> triggerLevels=new HashMap<Long,Long>();
        Map<Long,Long> buffLevels=new HashMap<Long,Long>();
        for(ProtoWire.Field field:role.fields){
            if(field.number!=2 || field.type!=2)continue;
            ProtoWire info=ProtoWire.parse(field.data);
            long sid=info.number(1,0),wid=info.number(14,0);
            String key=Long.toString(sid);
            if(!owned.has(key))continue;
            ProtoWire saved=LocalEconomy.decode(owned.getString(key));
            long rank=saved.number(4,1),weaponLevel=saved.number(12,1);
            if(weaponLevel<1 || weaponLevel>Integer.MAX_VALUE)
                throw new IOException("Invalid saved weapon level for servant "+sid);
            long[] energy=energy(sid,rank);
            info.clear(9);
            for(int index=3;index<7;index++)info.add(9,energy[index]);
            servants.put(field,info.bytes());

            Set<Long> referencedTriggers=new HashSet<Long>(info.integers(6));
            for(long[] effect:WEAPON_EFFECTS){
                if(effect[0]!=sid || effect[1]!=wid)continue;
                if(!referencedTriggers.contains(effect[3]))
                    throw new IOException("Audited weapon trigger absent from selected servant: "+effect[3]);
                assign(spellLevels,effect[2],weaponLevel,"spell");
                assign(triggerLevels,effect[3],weaponLevel,"trigger");
                for(int index=4;index<effect.length;index++)
                    assign(buffLevels,effect[index],weaponLevel,"buff");
            }
        }

        ProtoWire unit=ProtoWire.parse(role.data(102));
        update(unit,1,2,spellLevels,"spell");
        update(unit,4,2,triggerLevels,"trigger");
        update(unit,2,3,buffLevels,"buff");
        // Commit only after all references and shared-effect levels have been validated.
        for(Map.Entry<ProtoWire.Field,byte[]> change:servants.entrySet())
            change.getKey().data=change.getValue();
        if(!spellLevels.isEmpty())role.set(102,unit.bytes());
        role.set(100,roleLevel);
    }

    private static long[] energy(long servant,long rank)throws IOException{
        for(long[] row:ENERGY)
            if(row[0]==servant && rank>=row[1] && rank<=row[2])return row;
        throw new IOException("Original energy row absent for servant "+servant+" rank "+rank);
    }

    private static void assign(Map<Long,Long> levels,long id,long level,String kind)throws IOException{
        Long previous=levels.get(id);
        if(previous!=null && previous.longValue()!=level)
            throw new IOException("Conflicting selected weapon levels for shared "+kind+" "+id);
        levels.put(id,level);
    }

    private static void update(ProtoWire unit,int fieldNumber,int idField,
                               Map<Long,Long> levels,String kind)throws IOException{
        Set<Long> found=new HashSet<Long>();
        for(ProtoWire.Field field:unit.fields){
            if(field.number!=fieldNumber || field.type!=2)continue;
            ProtoWire info=ProtoWire.parse(field.data);
            long id=info.number(idField,0);
            Long level=levels.get(id);
            if(level==null)continue;
            if(!found.add(id))throw new IOException("Duplicate combat "+kind+" ID "+id);
            info.set(1,level.longValue());field.data=info.bytes();
        }
        if(found.size()!=levels.size()){
            Set<Long> missing=new HashSet<Long>(levels.keySet());missing.removeAll(found);
            throw new IOException("Audited combat "+kind+" IDs absent: "+missing);
        }
    }
}
'''


def generate(args):
    seed = json.loads(args.seed.read_text(encoding="utf-8-sig"))
    catalog = seed["_catalog"]
    servant_ids = sorted(map(int, catalog["servants"]))
    if len(servant_ids) != 41:
        raise ValueError("Expected the 41 restored owned-servant templates")
    servants = table(args.original / "servant.txt")
    ranks = table(args.original / "servantrankinfo.txt")
    equips = table(args.original / "servantequip.txt")
    # Native UI formula adds equipment values after dividing the rank by 10000.
    # These preserved 2020 equips contain no energy attributes, so no missing
    # equipment term may silently be guessed or discarded.
    for row in equips.values():
        for slot in range(1, 6):
            if row.get("attribute_type" + str(slot)) in ("99", "100", "101", "102"):
                raise ValueError("Energy equipment requires a separately audited transport formula")

    energy_rows = []
    rank_count = 0
    for sid in servant_ids:
        base = int(servants[sid]["rank_info"])
        expected_ranks = sorted(map(int, catalog["ranks"][str(sid)]))
        if expected_ranks != list(range(1, 11)):
            raise ValueError(f"Unexpected catalog rank coverage for servant {sid}")
        for rank in expected_ranks:
            row = ranks[base * 100 + rank]
            if int(row["rank"]) != rank:
                raise ValueError("Original rank identity mismatch")
            energy = tuple(int(row[column]) for column in ENERGY_COLUMNS)
            if any(value < 0 or value > 2147483647 for value in energy):
                raise ValueError("Energy outside protobuf int32 range")
            rank_count += 1
            if (energy_rows and energy_rows[-1][0] == sid
                    and energy_rows[-1][2] == rank - 1
                    and tuple(energy_rows[-1][3:]) == energy):
                energy_rows[-1][2] = rank
            else:
                energy_rows.append([sid, rank, rank, *energy])

    evidence = json.loads(args.effects.read_text(encoding="utf-8-sig"))
    effect_rows = evidence["rows"]
    if len(effect_rows) != 95 or len({r["spellID"] for r in effect_rows}) != 95:
        raise ValueError("Expected the 95 audited distinct weapon effects")
    if len({r["triggerID"] for r in effect_rows}) != 95:
        raise ValueError("Audited weapon trigger IDs must be unique")
    effects = [[r["servantID"], r["weaponID"], r["spellID"], r["triggerID"],
                *sorted(set(r["directBuffIDArgs"]))] for r in effect_rows]
    effects.sort()
    role = wire(base64.b64decode(seed["/combat/role/info"]["base64"]))
    unit = wire(next(v for n, t, v in role if n == 102 and t == 2))
    unit_ids = {field: {number(wire(v), key) for n, t, v in unit if n == field and t == 2}
                for field, key in ((1, 2), (4, 2), (2, 3))}
    for effect in effects:
        if effect[0] not in servant_ids or str(effect[1]) not in catalog["weapons"]:
            raise ValueError("Weapon link outside restored catalog")
        if effect[2] not in unit_ids[1] or effect[3] not in unit_ids[4]:
            raise ValueError("Audited spell or trigger absent from fixture")
        if not set(effect[4:]).issubset(unit_ids[2]):
            raise ValueError("Audited direct buff absent from fixture")

    sources = [args.original / name for name in ("servant.txt", "servantrankinfo.txt", "servantequip.txt")]
    hashes = "\n".join("    // " + path.name + " " + hashlib.sha256(path.read_bytes()).hexdigest()
                       for path in sources)
    # Explanatory native evidence can be added to the audit without changing
    # generated source; bind only the exact stable links consumed at runtime.
    link_bytes = json.dumps(effects, ensure_ascii=True, separators=(",", ":")).encode("ascii")
    hashes += "\n    // Audited weapon links " + hashlib.sha256(link_bytes).hexdigest()
    java_rows = lambda rows: "\n".join("        {" + ",".join(str(value) + "L" for value in row) + "},"
                                      for row in rows)
    output = (JAVA.replace("%HASHES%", hashes).replace("%ENERGY%", java_rows(energy_rows))
              .replace("%EFFECTS%", java_rows(effects))).encode("utf-8")
    if args.check:
        if args.output.read_bytes() != output:
            raise ValueError("OriginalCombatRules.java differs from regenerated original inputs")
    else:
        args.output.write_bytes(output)
    print(json.dumps({"servants": len(servant_ids), "originalRankRows": rank_count,
                      "compressedEnergyRows": len(energy_rows), "weaponEffectRows": len(effects),
                      "directBuffIDs": len({buff for row in effects for buff in row[4:]}),
                      "javaSHA256": hashlib.sha256(output).hexdigest(), "checkOnly": args.check},
                     ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--original", type=Path, default=ORIGINAL)
    parser.add_argument("--seed", type=Path, default=PROJECT / "构建/战斗修复/offline_responses.json")
    parser.add_argument("--effects", type=Path, default=PROJECT / "验收/战斗全面核查/95条武器被动等级接入断言.json")
    parser.add_argument("--output", type=Path,
                        default=PROJECT / "legacy-server/src/com/codex/witchweapon/OriginalCombatRules.java")
    parser.add_argument("--check", action="store_true")
    generate(parser.parse_args())


if __name__ == "__main__":
    main()
